spring.application.name=spring-boot-demo
server.port=8080
server.servlet.context-path=/training
logging.level.root=INFO
logging.level.com.company.training.auditdemo=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [traceId:%X{traceId}] [%thread] [%logger{36}] %msg%n
