spring.application.name=jdbc-mybatis-demo
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/training_jdbc_demo?useSSL=false&serverTimezone=Asia/Taipei&characterEncoding=utf8
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=never
mybatis.mapper-locations=classpath*:mapper/*.xml
mybatis.type-aliases-package=com.company.training.jdbcdemo.model
mybatis.configuration.map-underscore-to-camel-case=true
logging.level.com.company.training.jdbcdemo=INFO